### ISSUE TITLE
[Bug] Monsters in Doorways Cannot Be Clicked

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#24]
Monsters adjacent to doorways cannot be clicked on (door is clicked instead, could be that the monsters are below the door tile?). If you look at the first image, monsters that show up below the door can't be clicked on (the bottom 2 orcs) however, the monster at the top is above the door and can be clicked on. I'm not sure why some monsters are below the doors and others are not. This mission specifically is from The Lost Prince. (Firefox & Chrome)

**Comment by Ryuasd** [comment]
Fixed.
