### ISSUE TITLE
Double clicking on a hero brings up their action menu

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#29]
This makes it more straightforward to perform actions, because your cursor/finger doesn't have to move far from your character, and you don't have to go through the hassle of going to the bottom of the page, finding your character, and then performing said action.

Not important ideas:
Pressing-and-holding the character could open a radial menu of the main actions around the character?
Right click functionality?

**Comment by Ryuasd** [comment]
Added in development version: Double click, right click, longpress, all open contextual menu for actions.
In the future, i'll try to implement the Radial menu.
