### ISSUE TITLE
Change Centering Icon

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#31]
I suggest replacing the "R" in the bottom right with either an eyeball or crosshairs graphic to indicate centering would be a nifty change. Here's a link to a royalty free one as an example: https://www.dreamstime.com/centering-object-solid-flat-color-icons-round-outlines-bonus-included-image269702356#res42520256

**Comment by Ryuasd** [comment]
Changed the icon in the new development version.
