### ISSUE TITLE
Change Monster Attack Icon

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#32]
A sword could be added next to the numbers (that are next to the monsters), to indicate that the number is how much attack they have? Since the monsters on Zargon's turn show the dice count they roll anyways, it might be more useful to remove the numbers entirely or better yet have the numbers as a setting toggle.

**Comment by Ryuasd** [comment]
The number that you see, is not the Attack, but the Defense.
Is there, like in the Official App, because like that players can attack a monster without the need to click on the monster to check his defense.
I had anyway in mind to add a counter for the damages, but maybe with a setting toggle.
