### ISSUE TITLE
Slider Functionality

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#40]
Change the functionality of the "Zoom out" button above the centering button to include a zoom in as well (toggle in/out), or make the slider functional.

**Comment by Ryuasd** [comment]
I'm sorry but i don't understand well this, 
There are already both Zoom-Out an Zoom-In button, and changing the slider, change the zoom level, this not work for you?

**Comment by silent-arbiter** [comment]
See [Bug] Zooming Out Causes Visual Glitch. I believe this may be a formatting issue on Android version 14 causing the slider to not perform correctly, specifically on Firefox. Chrome has the correct slider functionality.

**Comment by Ryuasd** [comment]
Yes, was a bug on Firefox. Now is fixed!
