### ISSUE TITLE
Hamburger Menu Fullscreen

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#41]
Turn the Triple-Line button in the top right from a full-screen to a sidebar scaled to the text, rather than a fullscreen menu. Might look slightly cleaner, as it looks kind of silly with a ton of black empty space on desktop. If implemented, would need to decide if the application is still usable (moving around the board, clicking on objects, etc.) and/or if clicking off the sidebar would close the sidebar.

**Comment by Ryuasd** [comment]
This is already under development, with a rework of the UI!

**Comment by Ryuasd** [comment]
Done in new UI!
