### ISSUE TITLE
Adding Hotkeys

### ISSUE THREAD

**Issue by silent-arbiter** [Ryuasd/hQuestMaster#43]
- Adding hotkeys or shortcuts for common actions (would be desktop only)
- Adding hotkeys or shortcuts for selecting a hero (like 1 2 3 4 for slots 1 2 3 4)
- Adding a hotkey or shortcut for opening the selected character's action menu (like spacebar) (Also double clicking!)

**Comment by Ryuasd** [comment]
In new Development version added shortcut for heroes (number 1 to 9, for also NPC).
And added the space bar to also open the actions bar.

For other shortcuts, feel free to ask for them.
